[Feat] Performance Test
reiple/Collab pull request #22
Opened 2022-03-21 01:23 UTC by ysk1202

[Feat] Performance Test
testCnt 변수로 조절하며, 모든 Test Case에 대해 실행.
PC간 성능 차이일지는 모르겠으나.. 

아래의 실행 속도가 발생함.
  10회 - 1.26
  50회 - 4.16
  100회 - 6.98
  500회 - 31.72

Input Data 비율
  1. employeeNum	값 예시 : 69100000 ~ 69102000 / ... / 21100000 ~ 21102000
	▶ 비율 : 1:1

  2. name 값 예시 : "AAA AAA" ~ "ETT ETT"
	▶ 비율
	    - Full 기준 1:53
	    - First 기준 1:53
	    - Last 기준 1:53

  3. cl 값 예시 : CL2 ~ CL4	
	▶ 비율 : 1:35333

  4. phoneNum 값 예시 : 010-1000-1000 ~ 010-1000-2999 / 010-1001-1000 ~ 010-1001-2999/ ...
	▶ 비율 : 1:35333
	    - Full 기준 1:1
	    - Middle 기준 1:2000
	    - Last 기준 1:53

  5. birthday 값 예시 : 19510101 ~ 19511228 / 19510101~1951228 / ...
	▶ 비율 : 1:35333
	    - Full 기준 1:6
	    - yyyy 기준 1:2016
	    - mm 기준 1:8820 
	    - dd 기준 1:3785 

  6. cl 값 예시 : ADV ~ EX
	▶ 비율 : 1:35333

2022-03-21 01:54 UTC, likebullet86 commented on src/test/java/collab/PerformanceTest.java
> +    for(int i=0; i<106000; i++) {
10600 inputnum 갯수를 설정할수 있도록 변수로 설정하는게 좋을것 같습니다!

2022-03-21 01:54 UTC, likebullet86 reviewed
실험 결과로 보았을때는, hash를 쓰지 않아도 성능에 큰 문제는 없는것 같습니다!

2022-03-21 02:38 UTC, reiple requested changes
패키지명 수정이 필요해 보입니다.

2022-03-21 04:21 UTC, likebullet86 approved these changes
실험 결과로 보았을때는, hash를 쓰지 않아도 성능에 큰 문제는 없는것 같습니다!

2022-03-21 04:25 UTC, reiple requested changes
Test 클래스들이 import문 수정이 필요할 것 같습니다.

2022-03-21 04:25 UTC, reiple commented on src/test/java/collab/DeleteTest.java
> +import main.java.collab.Employee;
같은 패키지라서 import문이 필요 없을 것 같은데요.
혹시 넣으신 이유가 있을까요?

```suggestion
import collab.DataBase;
import collab.Employee;
```

2022-03-21 04:25 UTC, reiple commented on src/test/java/collab/ModifyTest.java
> +import main.java.collab.Employee;
같은 패키지라서 import문이 필요 없을 것 같은데요.
혹시 넣으신 이유가 있을까요?

2022-03-21 04:25 UTC, reiple commented on src/test/java/collab/SearchTest.java
> +import main.java.collab.Employee;
같은 패키지라서 import문이 필요 없을 것 같은데요.
혹시 넣으신 이유가 있을까요?

2022-03-21 04:37 UTC, reiple commented
성능 평가가 필요했는데 적절한 시점에 모두에게 필요한 좋은 코드를 만들어 주신 것 같습니다.
감사합니다!

2022-03-21 04:44 UTC, reiple approved these changes
패키지 확인하였습니다. 잘 동작하네요.

2022-03-21 13:39 UTC, likebullet86 approved these changes
성능 관련 테스트 작성하느라 수고하셨습니다!

2022-03-22 09:13 UTC, ysk1202 commented
해당 건은 DATABASE OBJECT의 변경이 많아 자체 CLOSE합니다.

2022-03-22 09:13 UTC, closed without merging